baseurl: /R3.01-DeveloppementWeb
permalink: /:categories/:title

markdown: kramdown
# highlighter: rouge

kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false

# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5677    # If you don't want to use the default port